// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by tools/gen_migrations_header.py from /home/yuxin/Code/FreezerManager/src/storage/postgres/migrations/*.sql.
// DO NOT EDIT. Edit the .sql files and regenerate.
#ifndef FMGR_POSTGRESMIGRATIONSEMBEDDED_H
#define FMGR_POSTGRESMIGRATIONSEMBEDDED_H

#include "storage/EmbeddedMigration.h"

#include <array>

namespace fmgr::storage {

  inline constexpr std::array<EmbeddedMigration, 15> k_postgres_embedded_migrations{{
      {1, "0001_init",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS audit_events (
  id               TEXT   PRIMARY KEY,
  at_micros        BIGINT NOT NULL,
  actor_user_id    TEXT   NOT NULL,
  actor_session_id TEXT   NOT NULL,
  lab_id           TEXT,
  action           TEXT   NOT NULL,
  entity_kind      TEXT   NOT NULL,
  entity_id        TEXT,
  before_json      TEXT   NOT NULL DEFAULT '{}',
  after_json       TEXT   NOT NULL DEFAULT '{}',
  request_id       TEXT   NOT NULL,
  prev_hash        TEXT   NOT NULL,
  this_hash        TEXT   NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS audit_events_at_idx          ON audit_events(at_micros);
CREATE INDEX IF NOT EXISTS audit_events_actor_idx       ON audit_events(actor_user_id);
CREATE INDEX IF NOT EXISTS audit_events_entity_kind_idx ON audit_events(entity_kind);
CREATE INDEX IF NOT EXISTS audit_events_lab_idx         ON audit_events(lab_id);

CREATE OR REPLACE FUNCTION fmgr_audit_immutable()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_events is append-only: % are not permitted', TG_OP;
END; $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'audit_events_no_update') THEN
    CREATE TRIGGER audit_events_no_update
      BEFORE UPDATE ON audit_events
      FOR EACH ROW EXECUTE FUNCTION fmgr_audit_immutable();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'audit_events_no_delete') THEN
    CREATE TRIGGER audit_events_no_delete
      BEFORE DELETE ON audit_events
      FOR EACH ROW EXECUTE FUNCTION fmgr_audit_immutable();
  END IF;
END $$;
)FMGRSQL"},
      {2, "0002_identity",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS labs (
  id                 TEXT    PRIMARY KEY,
  name               TEXT    NOT NULL CHECK (length(name) > 0),
  contact            TEXT    NOT NULL,
  created_at_micros  BIGINT  NOT NULL,
  settings_json      JSONB   NOT NULL DEFAULT '{}',
  is_phi_enabled     BOOLEAN NOT NULL DEFAULT FALSE,
  archived_at_micros BIGINT
);
CREATE TABLE IF NOT EXISTS users (
  id                  TEXT   PRIMARY KEY,
  primary_email       TEXT   NOT NULL CHECK (length(primary_email) > 2),
  display_name        TEXT   NOT NULL CHECK (length(display_name) > 0),
  status              TEXT   NOT NULL CHECK (status IN ('active', 'disabled')),
  created_at_micros   BIGINT NOT NULL,
  auth_bindings_json  JSONB  NOT NULL DEFAULT '[]',
  totp_secret_enc     TEXT,
  default_lab_id      TEXT   REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX IF NOT EXISTS users_primary_email_lower_unique
  ON users(lower(primary_email));
CREATE TABLE IF NOT EXISTS lab_memberships (
  user_id            TEXT   NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  lab_id             TEXT   NOT NULL REFERENCES labs(id)  DEFERRABLE INITIALLY DEFERRED,
  scope_filters_json JSONB  NOT NULL DEFAULT '{}',
  invited_by         TEXT   REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  joined_at_micros   BIGINT NOT NULL,
  revoked_at_micros  BIGINT,
  role_id            TEXT,
  PRIMARY KEY (user_id, lab_id)
);
)FMGRSQL"},
      {3, "0003_roles",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS permissions (
  key         TEXT PRIMARY KEY,
  description TEXT NOT NULL CHECK (length(description) > 0)
);
CREATE TABLE IF NOT EXISTS roles (
  id                 TEXT    PRIMARY KEY,
  lab_id             TEXT    REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  kind               TEXT    NOT NULL CHECK (kind IN
    ('system_admin','lab_admin','member','read_only','api_client','custom')),
  name               TEXT    NOT NULL CHECK (length(name) > 0),
  description        TEXT    NOT NULL,
  is_builtin         BOOLEAN NOT NULL DEFAULT FALSE,
  created_at_micros  BIGINT  NOT NULL,
  archived_at_micros BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS roles_builtin_name_unique
  ON roles(name) WHERE lab_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS roles_lab_name_unique
  ON roles(lab_id, name) WHERE lab_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id        TEXT NOT NULL REFERENCES roles(id)       DEFERRABLE INITIALLY DEFERRED,
  permission_key TEXT NOT NULL REFERENCES permissions(key) DEFERRABLE INITIALLY DEFERRED,
  PRIMARY KEY (role_id, permission_key)
);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'lab_memberships_role_id_fk'
  ) THEN
    ALTER TABLE lab_memberships
      ADD CONSTRAINT lab_memberships_role_id_fk
      FOREIGN KEY (role_id) REFERENCES roles(id) DEFERRABLE INITIALLY DEFERRED;
  END IF;
END $$;
INSERT INTO permissions (key, description) VALUES
  ('sample.read','Read sample records.'),
  ('sample.write','Create or modify samples.'),
  ('sample.checkout','Check samples in or out.'),
  ('sample.delete_soft','Tombstone a sample.'),
  ('sample.delete_hard','Permanently delete tombstoned sample (SystemAdmin only).'),
  ('box.configure','Define or modify boxes and box types.'),
  ('freezer.configure','Configure freezers and storage layout.'),
  ('custom_field.define','Define custom field schemas.'),
  ('item_type.define','Define item-type taxonomy.'),
  ('user.invite','Invite or revoke lab members.'),
  ('user.manage_roles','Assign roles to lab members.'),
  ('audit.read','Browse audit log entries.'),
  ('audit.export','Export signed audit log files.'),
  ('backup.run','Trigger a backup or restore-drill.'),
  ('share.request','Open a cross-lab share request.'),
  ('share.approve','Approve or reject a share request.'),
  ('phi.read','Read PHI-tagged custom fields.'),
  ('lab.configure','Modify lab settings.'),
  ('lab.enable_phi','Toggle PHI mode on a lab.'),
  ('key.rotate','Rotate cryptographic keys.'),
  ('session.revoke','Revoke another user''s sessions.')
  ON CONFLICT (key) DO NOTHING;
INSERT INTO roles (id,lab_id,kind,name,description,is_builtin,created_at_micros) VALUES
  ('00000000-0000-0000-0000-000000000001',NULL,'system_admin','SystemAdmin',
   'Deployment-wide administrator (PHI access requires separate grant).',TRUE,0),
  ('00000000-0000-0000-0000-000000000002',NULL,'lab_admin','LabAdmin',
   'Full administrative control of one lab.',TRUE,0),
  ('00000000-0000-0000-0000-000000000003',NULL,'member','Member',
   'Read+write samples within scoped freezers/projects.',TRUE,0),
  ('00000000-0000-0000-0000-000000000004',NULL,'read_only','ReadOnly',
   'Read-only access; cannot check out.',TRUE,0),
  ('00000000-0000-0000-0000-000000000005',NULL,'api_client','ApiClient',
   'Conservative machine-client default; expand via custom roles.',TRUE,0)
  ON CONFLICT (id) DO NOTHING;
INSERT INTO role_permissions (role_id,permission_key) VALUES
  ('00000000-0000-0000-0000-000000000001','sample.read'),
  ('00000000-0000-0000-0000-000000000001','sample.write'),
  ('00000000-0000-0000-0000-000000000001','sample.checkout'),
  ('00000000-0000-0000-0000-000000000001','sample.delete_soft'),
  ('00000000-0000-0000-0000-000000000001','sample.delete_hard'),
  ('00000000-0000-0000-0000-000000000001','box.configure'),
  ('00000000-0000-0000-0000-000000000001','freezer.configure'),
  ('00000000-0000-0000-0000-000000000001','custom_field.define'),
  ('00000000-0000-0000-0000-000000000001','item_type.define'),
  ('00000000-0000-0000-0000-000000000001','user.invite'),
  ('00000000-0000-0000-0000-000000000001','user.manage_roles'),
  ('00000000-0000-0000-0000-000000000001','audit.read'),
  ('00000000-0000-0000-0000-000000000001','audit.export'),
  ('00000000-0000-0000-0000-000000000001','backup.run'),
  ('00000000-0000-0000-0000-000000000001','share.request'),
  ('00000000-0000-0000-0000-000000000001','share.approve'),
  ('00000000-0000-0000-0000-000000000001','lab.configure'),
  ('00000000-0000-0000-0000-000000000001','lab.enable_phi'),
  ('00000000-0000-0000-0000-000000000001','key.rotate'),
  ('00000000-0000-0000-0000-000000000001','session.revoke'),
  ('00000000-0000-0000-0000-000000000002','sample.read'),
  ('00000000-0000-0000-0000-000000000002','sample.write'),
  ('00000000-0000-0000-0000-000000000002','sample.checkout'),
  ('00000000-0000-0000-0000-000000000002','sample.delete_soft'),
  ('00000000-0000-0000-0000-000000000002','box.configure'),
  ('00000000-0000-0000-0000-000000000002','freezer.configure'),
  ('00000000-0000-0000-0000-000000000002','custom_field.define'),
  ('00000000-0000-0000-0000-000000000002','item_type.define'),
  ('00000000-0000-0000-0000-000000000002','user.invite'),
  ('00000000-0000-0000-0000-000000000002','user.manage_roles'),
  ('00000000-0000-0000-0000-000000000002','audit.read'),
  ('00000000-0000-0000-0000-000000000002','audit.export'),
  ('00000000-0000-0000-0000-000000000002','share.request'),
  ('00000000-0000-0000-0000-000000000002','share.approve'),
  ('00000000-0000-0000-0000-000000000002','lab.configure'),
  ('00000000-0000-0000-0000-000000000003','sample.read'),
  ('00000000-0000-0000-0000-000000000003','sample.write'),
  ('00000000-0000-0000-0000-000000000003','sample.checkout'),
  ('00000000-0000-0000-0000-000000000003','sample.delete_soft'),
  ('00000000-0000-0000-0000-000000000003','share.request'),
  ('00000000-0000-0000-0000-000000000004','sample.read'),
  ('00000000-0000-0000-0000-000000000004','audit.read'),
  ('00000000-0000-0000-0000-000000000005','sample.read'),
  ('00000000-0000-0000-0000-000000000005','sample.checkout')
  ON CONFLICT DO NOTHING;
)FMGRSQL"},
      {4, "0004_layout",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS storage_containers (
  id                 TEXT   PRIMARY KEY,
  lab_id             TEXT   NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  parent_id          TEXT   REFERENCES storage_containers(id) DEFERRABLE INITIALLY DEFERRED,
  kind               TEXT   NOT NULL CHECK (kind IN
    ('compartment','shelf','rack','drawer','custom')),
  name               TEXT   NOT NULL CHECK (length(name) > 0),
  label              TEXT   NOT NULL,
  ordering_index     BIGINT NOT NULL DEFAULT 0,
  capacity_hint_json JSONB  NOT NULL DEFAULT '{}',
  created_at_micros  BIGINT NOT NULL,
  archived_at_micros BIGINT,
  CHECK (id <> parent_id)
);
CREATE INDEX IF NOT EXISTS storage_containers_parent_idx ON storage_containers(parent_id);
CREATE INDEX IF NOT EXISTS storage_containers_lab_idx    ON storage_containers(lab_id);
CREATE TABLE IF NOT EXISTS freezers (
  id                 TEXT             PRIMARY KEY,
  lab_id             TEXT             NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  name               TEXT             NOT NULL CHECK (length(name) > 0),
  location           TEXT             NOT NULL,
  model              TEXT             NOT NULL,
  temp_target_c      DOUBLE PRECISION,
  layout_root_id     TEXT             NOT NULL
    REFERENCES storage_containers(id) DEFERRABLE INITIALLY DEFERRED,
  created_at_micros  BIGINT           NOT NULL,
  archived_at_micros BIGINT
);
CREATE INDEX IF NOT EXISTS freezers_lab_id_idx ON freezers(lab_id);
CREATE UNIQUE INDEX IF NOT EXISTS freezers_lab_name_unique
  ON freezers(lab_id, name) WHERE archived_at_micros IS NULL;
ALTER TABLE storage_containers ENABLE ROW LEVEL SECURITY;
ALTER TABLE storage_containers FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_storage_containers_lab ON storage_containers USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
ALTER TABLE freezers ENABLE ROW LEVEL SECURITY;
ALTER TABLE freezers FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_freezers_lab ON freezers USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
)FMGRSQL"},
      {5, "0005_box_types",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS container_types (
  id                    TEXT   PRIMARY KEY,
  lab_id                TEXT   NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  name                  TEXT   NOT NULL CHECK (length(name) > 0),
  size_class            TEXT   NOT NULL CHECK (length(size_class) > 0),
  outer_dimensions_json JSONB  NOT NULL DEFAULT '{}',
  material              TEXT   NOT NULL,
  supplier_sku          TEXT   NOT NULL,
  created_at_micros     BIGINT NOT NULL,
  archived_at_micros    BIGINT
);
CREATE INDEX IF NOT EXISTS container_types_lab_idx           ON container_types(lab_id);
CREATE INDEX IF NOT EXISTS container_types_lab_size_class_idx ON container_types(lab_id,size_class);
CREATE TABLE IF NOT EXISTS box_types (
  id                 TEXT   PRIMARY KEY,
  lab_id             TEXT   NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  name               TEXT   NOT NULL CHECK (length(name) > 0),
  manufacturer       TEXT   NOT NULL,
  sku                TEXT   NOT NULL,
  created_at_micros  BIGINT NOT NULL,
  archived_at_micros BIGINT
);
CREATE INDEX IF NOT EXISTS box_types_lab_idx ON box_types(lab_id);
CREATE UNIQUE INDEX IF NOT EXISTS box_types_lab_name_unique
  ON box_types(lab_id, name) WHERE archived_at_micros IS NULL;
CREATE TABLE IF NOT EXISTS box_type_positions (
  box_type_id TEXT    NOT NULL
    REFERENCES box_types(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  label       TEXT    NOT NULL CHECK (length(label) > 0),
  row_index   INTEGER NOT NULL CHECK (row_index >= 0),
  col_index   INTEGER NOT NULL CHECK (col_index >= 0),
  z_index     INTEGER CHECK (z_index IS NULL OR z_index >= 0),
  PRIMARY KEY (box_type_id, label)
);
CREATE TABLE IF NOT EXISTS box_type_position_accepts (
  box_type_id    TEXT NOT NULL,
  position_label TEXT NOT NULL,
  size_class     TEXT NOT NULL CHECK (length(size_class) > 0),
  PRIMARY KEY (box_type_id, position_label, size_class),
  FOREIGN KEY (box_type_id, position_label)
    REFERENCES box_type_positions(box_type_id, label)
    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE container_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE container_types FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_container_types_lab ON container_types USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
ALTER TABLE box_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE box_types FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_box_types_lab ON box_types USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
)FMGRSQL"},
      {6, "0006_boxes",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS boxes (
  id                   TEXT   PRIMARY KEY,
  lab_id               TEXT   NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  box_type_id          TEXT   NOT NULL REFERENCES box_types(id) DEFERRABLE INITIALLY DEFERRED,
  storage_container_id TEXT   NOT NULL
    REFERENCES storage_containers(id) DEFERRABLE INITIALLY DEFERRED,
  label                TEXT   NOT NULL CHECK (length(label) > 0),
  serial               TEXT,
  barcode              TEXT,
  created_at_micros    BIGINT NOT NULL,
  archived_at_micros   BIGINT
);
CREATE INDEX IF NOT EXISTS boxes_lab_idx              ON boxes(lab_id);
CREATE INDEX IF NOT EXISTS boxes_storage_container_idx ON boxes(storage_container_id);
CREATE INDEX IF NOT EXISTS boxes_box_type_idx         ON boxes(box_type_id);
CREATE UNIQUE INDEX IF NOT EXISTS boxes_lab_label_unique
  ON boxes(lab_id, label) WHERE archived_at_micros IS NULL;
ALTER TABLE boxes ENABLE ROW LEVEL SECURITY;
ALTER TABLE boxes FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_boxes_lab ON boxes USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
)FMGRSQL"},
      {7, "0007_item_types",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS item_types (
  id                 TEXT   PRIMARY KEY,
  lab_id             TEXT   NOT NULL REFERENCES labs(id)       DEFERRABLE INITIALLY DEFERRED,
  parent_id          TEXT   REFERENCES item_types(id)          DEFERRABLE INITIALLY DEFERRED,
  name               TEXT   NOT NULL CHECK (length(name) > 0),
  created_at_micros  BIGINT NOT NULL,
  archived_at_micros BIGINT,
  CHECK (id <> parent_id)
);
CREATE INDEX IF NOT EXISTS item_types_lab_idx    ON item_types(lab_id);
CREATE INDEX IF NOT EXISTS item_types_parent_idx ON item_types(parent_id);
CREATE UNIQUE INDEX IF NOT EXISTS item_types_lab_name_unique
  ON item_types(lab_id, name) WHERE archived_at_micros IS NULL;
CREATE TABLE IF NOT EXISTS custom_field_definitions (
  id                 TEXT    PRIMARY KEY,
  lab_id             TEXT    NOT NULL REFERENCES labs(id)       DEFERRABLE INITIALLY DEFERRED,
  scope_kind         TEXT    NOT NULL
    CHECK (scope_kind IN ('sample','box','freezer','container')),
  item_type_id       TEXT    REFERENCES item_types(id)          DEFERRABLE INITIALLY DEFERRED,
  key                TEXT    NOT NULL CHECK (length(key) > 0),
  label              TEXT    NOT NULL CHECK (length(label) > 0),
  data_type          TEXT    NOT NULL,
  required           BOOLEAN NOT NULL DEFAULT FALSE,
  validation_json    JSONB   NOT NULL DEFAULT '{}',
  indexed            BOOLEAN NOT NULL DEFAULT FALSE,
  is_phi             BOOLEAN NOT NULL DEFAULT FALSE,
  created_at_micros  BIGINT  NOT NULL,
  archived_at_micros BIGINT
);
CREATE INDEX IF NOT EXISTS cfd_lab_idx  ON custom_field_definitions(lab_id);
CREATE INDEX IF NOT EXISTS cfd_type_idx ON custom_field_definitions(item_type_id);
CREATE UNIQUE INDEX IF NOT EXISTS cfd_lab_scope_type_key_unique
  ON custom_field_definitions(lab_id, scope_kind, COALESCE(item_type_id,''), key)
  WHERE archived_at_micros IS NULL;
ALTER TABLE item_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE item_types FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_item_types_lab ON item_types USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
ALTER TABLE custom_field_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_field_definitions FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_cfd_lab ON custom_field_definitions USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
)FMGRSQL"},
      {8, "0008_samples",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS projects (
  id                 TEXT   PRIMARY KEY,
  lab_id             TEXT   NOT NULL REFERENCES labs(id)  DEFERRABLE INITIALLY DEFERRED,
  name               TEXT   NOT NULL CHECK (length(name) > 0),
  owner_user_id      TEXT   NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  created_at_micros  BIGINT NOT NULL,
  archived_at_micros BIGINT
);
CREATE INDEX IF NOT EXISTS projects_lab_idx ON projects(lab_id);
CREATE UNIQUE INDEX IF NOT EXISTS projects_lab_name_unique
  ON projects(lab_id, name) WHERE archived_at_micros IS NULL;
CREATE TABLE IF NOT EXISTS samples (
  id                      TEXT  PRIMARY KEY,
  lab_id                  TEXT  NOT NULL REFERENCES labs(id)           DEFERRABLE INITIALLY DEFERRED,
  item_type_id            TEXT  NOT NULL REFERENCES item_types(id)     DEFERRABLE INITIALLY DEFERRED,
  name                    TEXT  NOT NULL CHECK (length(name) > 0),
  barcode                 TEXT,
  container_type_id       TEXT  REFERENCES container_types(id)         DEFERRABLE INITIALLY DEFERRED,
  box_id                  TEXT  REFERENCES boxes(id)                   DEFERRABLE INITIALLY DEFERRED,
  position_label          TEXT,
  volume_value            BIGINT,
  volume_unit             TEXT,
  mass_value              BIGINT,
  mass_unit               TEXT,
  status                  TEXT  NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','checked_out','depleted','destroyed','tombstoned')),
  parent_sample_id        TEXT  REFERENCES samples(id)                 DEFERRABLE INITIALLY DEFERRED,
  created_by              TEXT  NOT NULL,
  created_at_micros       BIGINT NOT NULL,
  last_modified_by        TEXT  NOT NULL,
  last_modified_at_micros BIGINT NOT NULL,
  custom_fields_json      JSONB NOT NULL DEFAULT '{}',
  phi_fields_enc_json     JSONB NOT NULL DEFAULT '{}',
  CHECK ((box_id IS NULL) = (position_label IS NULL))
);
CREATE INDEX IF NOT EXISTS samples_lab_idx    ON samples(lab_id);
CREATE INDEX IF NOT EXISTS samples_box_idx    ON samples(box_id);
CREATE INDEX IF NOT EXISTS samples_parent_idx ON samples(parent_sample_id);
CREATE INDEX IF NOT EXISTS samples_status_idx ON samples(status);
CREATE UNIQUE INDEX IF NOT EXISTS samples_position_unique
  ON samples(box_id, position_label)
  WHERE status IN ('active','checked_out') AND box_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS sample_projects (
  sample_id  TEXT NOT NULL REFERENCES samples(id)  DEFERRABLE INITIALLY DEFERRED,
  project_id TEXT NOT NULL REFERENCES projects(id) DEFERRABLE INITIALLY DEFERRED,
  PRIMARY KEY (sample_id, project_id)
);
CREATE TABLE IF NOT EXISTS checkout_events (
  id             TEXT   PRIMARY KEY,
  sample_id      TEXT   NOT NULL REFERENCES samples(id) DEFERRABLE INITIALLY DEFERRED,
  lab_id         TEXT   NOT NULL REFERENCES labs(id)    DEFERRABLE INITIALLY DEFERRED,
  user_id        TEXT   NOT NULL REFERENCES users(id)   DEFERRABLE INITIALLY DEFERRED,
  action         TEXT   NOT NULL CHECK (action IN ('out','in','destroy')),
  reason         TEXT,
  at_micros      BIGINT NOT NULL,
  volume_delta   BIGINT,
  volume_unit    TEXT,
  location_after TEXT
);
CREATE INDEX IF NOT EXISTS checkout_events_sample_idx ON checkout_events(sample_id);
CREATE INDEX IF NOT EXISTS checkout_events_lab_idx    ON checkout_events(lab_id);
CREATE INDEX IF NOT EXISTS checkout_events_user_idx   ON checkout_events(user_id);
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_projects_lab ON projects USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
ALTER TABLE samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE samples FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_samples_lab ON samples USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
ALTER TABLE checkout_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkout_events FORCE ROW LEVEL SECURITY;
CREATE POLICY fmgr_checkout_events_lab ON checkout_events USING (
  lab_id = ANY(string_to_array(current_setting('app.current_lab_ids', true), ',')));
)FMGRSQL"},
      {9, "0009_share_requests",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS share_requests (
  id                TEXT   PRIMARY KEY,
  source_lab_id     TEXT   NOT NULL REFERENCES labs(id)  DEFERRABLE INITIALLY DEFERRED,
  target_lab_id     TEXT   NOT NULL REFERENCES labs(id)  DEFERRABLE INITIALLY DEFERRED,
  requested_by      TEXT   NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  scope_json        TEXT   NOT NULL DEFAULT '{}',
  status            TEXT   NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','approved','rejected','revoked')),
  created_at_micros BIGINT NOT NULL,
  decided_at_micros BIGINT,
  CHECK (source_lab_id != target_lab_id)
);
CREATE INDEX IF NOT EXISTS share_requests_source_lab_idx ON share_requests(source_lab_id);
CREATE INDEX IF NOT EXISTS share_requests_target_lab_idx ON share_requests(target_lab_id);
CREATE INDEX IF NOT EXISTS share_requests_status_idx     ON share_requests(status);
CREATE TABLE IF NOT EXISTS share_request_approvals (
  share_request_id  TEXT   NOT NULL REFERENCES share_requests(id) DEFERRABLE INITIALLY DEFERRED,
  approver_role     TEXT   NOT NULL
    CHECK (approver_role IN ('source_admin','target_admin','system_admin')),
  approver_user_id  TEXT   NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  decided_at_micros BIGINT NOT NULL,
  note              TEXT,
  PRIMARY KEY (share_request_id, approver_role)
);
CREATE INDEX IF NOT EXISTS share_request_approvals_request_idx
  ON share_request_approvals(share_request_id);
)FMGRSQL"},
      {10, "0010_sessions",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS sessions (
  id                  TEXT   PRIMARY KEY,
  user_id             TEXT   NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  token_hash          TEXT   NOT NULL CHECK (length(token_hash) > 0),
  token_prefix        TEXT   NOT NULL CHECK (length(token_prefix) > 0),
  created_at_micros   BIGINT NOT NULL,
  last_seen_at_micros BIGINT NOT NULL,
  ip                  TEXT,
  user_agent          TEXT,
  revoked_at_micros   BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS sessions_prefix_active_unique
  ON sessions(token_prefix) WHERE revoked_at_micros IS NULL;
CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);
CREATE TABLE IF NOT EXISTS api_tokens (
  id                TEXT   PRIMARY KEY,
  user_id           TEXT   NOT NULL REFERENCES users(id)  DEFERRABLE INITIALLY DEFERRED,
  lab_id            TEXT   REFERENCES labs(id)            DEFERRABLE INITIALLY DEFERRED,
  name              TEXT   NOT NULL CHECK (length(name) > 0),
  scope_json        TEXT   NOT NULL DEFAULT '[]',
  token_hash        TEXT   NOT NULL CHECK (length(token_hash) > 0),
  token_prefix      TEXT   NOT NULL CHECK (length(token_prefix) > 0),
  created_at_micros BIGINT NOT NULL,
  expires_at_micros BIGINT,
  revoked_at_micros BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS api_tokens_prefix_active_unique
  ON api_tokens(token_prefix) WHERE revoked_at_micros IS NULL;
CREATE INDEX IF NOT EXISTS api_tokens_user_id_idx ON api_tokens(user_id);
CREATE INDEX IF NOT EXISTS api_tokens_lab_id_idx  ON api_tokens(lab_id);
)FMGRSQL"},
      {11, "0011_audit_events_full",
       R"FMGRSQL(SELECT 1; -- no-op: audit_events already has full schema from migration 1)FMGRSQL"},
      {12, "0012_sessions_mfa",
       R"FMGRSQL(
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS mfa_complete BOOLEAN NOT NULL DEFAULT TRUE;
)FMGRSQL"},
      {13, "0013_authz_version",
       R"FMGRSQL(
-- Authorization epoch for permission-cache invalidation. Bumped in-transaction
-- whenever a user's effective permissions change (membership/role/grant). Auth
-- providers key their resolved-permission cache on this value so a downgrade
-- takes effect on the next request rather than waiting for the cache TTL.
ALTER TABLE users ADD COLUMN IF NOT EXISTS authz_version BIGINT NOT NULL DEFAULT 0;
)FMGRSQL"},
      {14, "0014_lab_provision",
       R"FMGRSQL(
-- Global-only permission for deployment-level lab provisioning (LabService/CreateLab).
-- Creating a brand-new lab cannot be gated by a per-lab permission because no
-- membership exists yet; it is a SystemAdmin deployment action. Granted to the
-- built-in SystemAdmin role only.
INSERT INTO permissions (key, description) VALUES
  ('lab.provision', 'Provision (create) new labs (SystemAdmin only).')
  ON CONFLICT (key) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_key) VALUES
  ('00000000-0000-0000-0000-000000000001', 'lab.provision')
  ON CONFLICT DO NOTHING;
)FMGRSQL"},
      {15, "0015_login_attempt",
       R"FMGRSQL(
-- C-1: Persistent login-lockout state. Failed-login counters must survive a
-- process restart, otherwise an attacker bypasses the account lockout by
-- bouncing freezerd. Keyed by lowercased email; not lab-scoped (the lockout
-- check runs pre-authentication, before any lab context exists), so NO RLS —
-- mirrors the user-scoped sessions table. One active row per email: a
-- successful login clears the row via cleared_at_micros; the partial unique
-- index allows a fresh active row on the next failure.
CREATE TABLE IF NOT EXISTS login_attempts (
  id                    TEXT    PRIMARY KEY,
  email                 TEXT    NOT NULL CHECK (length(email) > 0),
  failure_count         BIGINT  NOT NULL DEFAULT 0,
  locked_until_micros   BIGINT,
  last_activity_micros  BIGINT  NOT NULL,
  cleared_at_micros     BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS login_attempts_email_active_unique
  ON login_attempts(email) WHERE cleared_at_micros IS NULL;
)FMGRSQL"},
  }};

} // namespace fmgr::storage

#endif // FMGR_POSTGRESMIGRATIONSEMBEDDED_H
