// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by tools/gen_migrations_header.py from /home/yuxin/Code/FreezerManager/src/storage/sqlite/migrations/*.sql.
// DO NOT EDIT. Edit the .sql files and regenerate.
#ifndef FMGR_SQLITEMIGRATIONSEMBEDDED_H
#define FMGR_SQLITEMIGRATIONSEMBEDDED_H

#include "storage/EmbeddedMigration.h"

#include <array>

namespace fmgr::storage {

  inline constexpr std::array<EmbeddedMigration, 15> k_sqlite_embedded_migrations{{
      {1, "0001_init",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS audit_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_name TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  actor_user_id TEXT NOT NULL,
  actor_session_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  reason TEXT NOT NULL
);
)FMGRSQL"},
      {2, "0002_identity",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS labs (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL CHECK (length(name) > 0),
  contact TEXT NOT NULL,
  created_at_micros INTEGER NOT NULL,
  settings_json TEXT NOT NULL CHECK (json_valid(settings_json)),
  is_phi_enabled INTEGER NOT NULL CHECK (is_phi_enabled IN (0, 1)),
  archived_at_micros INTEGER
);

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  primary_email TEXT NOT NULL CHECK (length(primary_email) > 2),
  display_name TEXT NOT NULL CHECK (length(display_name) > 0),
  status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
  created_at_micros INTEGER NOT NULL,
  auth_bindings_json TEXT NOT NULL CHECK (json_valid(auth_bindings_json)),
  totp_secret_enc TEXT,
  default_lab_id TEXT REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE UNIQUE INDEX IF NOT EXISTS users_primary_email_lower_unique
  ON users(lower(primary_email));

CREATE TABLE IF NOT EXISTS lab_memberships (
  user_id TEXT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  lab_id TEXT NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  scope_filters_json TEXT NOT NULL CHECK (json_valid(scope_filters_json)),
  invited_by TEXT REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  joined_at_micros INTEGER NOT NULL,
  revoked_at_micros INTEGER,
  PRIMARY KEY (user_id, lab_id)
);
)FMGRSQL"},
      {3, "0003_roles",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS permissions (
  key TEXT PRIMARY KEY,
  description TEXT NOT NULL CHECK (length(description) > 0)
);

CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY,
  lab_id TEXT REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  kind TEXT NOT NULL CHECK (kind IN
    ('system_admin', 'lab_admin', 'member', 'read_only', 'api_client', 'custom')),
  name TEXT NOT NULL CHECK (length(name) > 0),
  description TEXT NOT NULL,
  is_builtin INTEGER NOT NULL CHECK (is_builtin IN (0, 1)),
  created_at_micros INTEGER NOT NULL,
  archived_at_micros INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS roles_builtin_name_unique
  ON roles(name) WHERE lab_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS roles_lab_name_unique
  ON roles(lab_id, name) WHERE lab_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id TEXT NOT NULL REFERENCES roles(id) DEFERRABLE INITIALLY DEFERRED,
  permission_key TEXT NOT NULL REFERENCES permissions(key) DEFERRABLE INITIALLY DEFERRED,
  PRIMARY KEY (role_id, permission_key)
);

ALTER TABLE lab_memberships
  ADD COLUMN role_id TEXT REFERENCES roles(id) DEFERRABLE INITIALLY DEFERRED;

INSERT INTO permissions (key, description) VALUES
  ('sample.read', 'Read sample records.'),
  ('sample.write', 'Create or modify samples.'),
  ('sample.checkout', 'Check samples in or out.'),
  ('sample.delete_soft', 'Tombstone a sample.'),
  ('sample.delete_hard', 'Permanently delete tombstoned sample (SystemAdmin only).'),
  ('box.configure', 'Define or modify boxes and box types.'),
  ('freezer.configure', 'Configure freezers and storage layout.'),
  ('custom_field.define', 'Define custom field schemas.'),
  ('item_type.define', 'Define item-type taxonomy.'),
  ('user.invite', 'Invite or revoke lab members.'),
  ('user.manage_roles', 'Assign roles to lab members.'),
  ('audit.read', 'Browse audit log entries.'),
  ('audit.export', 'Export signed audit log files.'),
  ('backup.run', 'Trigger a backup or restore-drill.'),
  ('share.request', 'Open a cross-lab share request.'),
  ('share.approve', 'Approve or reject a share request.'),
  ('phi.read', 'Read PHI-tagged custom fields.'),
  ('lab.configure', 'Modify lab settings.'),
  ('lab.enable_phi', 'Toggle PHI mode on a lab.'),
  ('key.rotate', 'Rotate cryptographic keys.'),
  ('session.revoke', 'Revoke another user''s sessions.');

INSERT INTO roles (id, lab_id, kind, name, description, is_builtin, created_at_micros) VALUES
  ('00000000-0000-0000-0000-000000000001', NULL, 'system_admin', 'SystemAdmin',
   'Deployment-wide administrator (PHI access requires separate grant).', 1, 0),
  ('00000000-0000-0000-0000-000000000002', NULL, 'lab_admin', 'LabAdmin',
   'Full administrative control of one lab.', 1, 0),
  ('00000000-0000-0000-0000-000000000003', NULL, 'member', 'Member',
   'Read+write samples within scoped freezers/projects.', 1, 0),
  ('00000000-0000-0000-0000-000000000004', NULL, 'read_only', 'ReadOnly',
   'Read-only access; cannot check out.', 1, 0),
  ('00000000-0000-0000-0000-000000000005', NULL, 'api_client', 'ApiClient',
   'Conservative machine-client default; expand via custom roles.', 1, 0);

INSERT INTO role_permissions (role_id, permission_key) VALUES
  ('00000000-0000-0000-0000-000000000001', 'sample.read'),
  ('00000000-0000-0000-0000-000000000001', 'sample.write'),
  ('00000000-0000-0000-0000-000000000001', 'sample.checkout'),
  ('00000000-0000-0000-0000-000000000001', 'sample.delete_soft'),
  ('00000000-0000-0000-0000-000000000001', 'sample.delete_hard'),
  ('00000000-0000-0000-0000-000000000001', 'box.configure'),
  ('00000000-0000-0000-0000-000000000001', 'freezer.configure'),
  ('00000000-0000-0000-0000-000000000001', 'custom_field.define'),
  ('00000000-0000-0000-0000-000000000001', 'item_type.define'),
  ('00000000-0000-0000-0000-000000000001', 'user.invite'),
  ('00000000-0000-0000-0000-000000000001', 'user.manage_roles'),
  ('00000000-0000-0000-0000-000000000001', 'audit.read'),
  ('00000000-0000-0000-0000-000000000001', 'audit.export'),
  ('00000000-0000-0000-0000-000000000001', 'backup.run'),
  ('00000000-0000-0000-0000-000000000001', 'share.request'),
  ('00000000-0000-0000-0000-000000000001', 'share.approve'),
  ('00000000-0000-0000-0000-000000000001', 'lab.configure'),
  ('00000000-0000-0000-0000-000000000001', 'lab.enable_phi'),
  ('00000000-0000-0000-0000-000000000001', 'key.rotate'),
  ('00000000-0000-0000-0000-000000000001', 'session.revoke'),
  ('00000000-0000-0000-0000-000000000002', 'sample.read'),
  ('00000000-0000-0000-0000-000000000002', 'sample.write'),
  ('00000000-0000-0000-0000-000000000002', 'sample.checkout'),
  ('00000000-0000-0000-0000-000000000002', 'sample.delete_soft'),
  ('00000000-0000-0000-0000-000000000002', 'box.configure'),
  ('00000000-0000-0000-0000-000000000002', 'freezer.configure'),
  ('00000000-0000-0000-0000-000000000002', 'custom_field.define'),
  ('00000000-0000-0000-0000-000000000002', 'item_type.define'),
  ('00000000-0000-0000-0000-000000000002', 'user.invite'),
  ('00000000-0000-0000-0000-000000000002', 'user.manage_roles'),
  ('00000000-0000-0000-0000-000000000002', 'audit.read'),
  ('00000000-0000-0000-0000-000000000002', 'audit.export'),
  ('00000000-0000-0000-0000-000000000002', 'share.request'),
  ('00000000-0000-0000-0000-000000000002', 'share.approve'),
  ('00000000-0000-0000-0000-000000000002', 'lab.configure'),
  ('00000000-0000-0000-0000-000000000003', 'sample.read'),
  ('00000000-0000-0000-0000-000000000003', 'sample.write'),
  ('00000000-0000-0000-0000-000000000003', 'sample.checkout'),
  ('00000000-0000-0000-0000-000000000003', 'sample.delete_soft'),
  ('00000000-0000-0000-0000-000000000003', 'share.request'),
  ('00000000-0000-0000-0000-000000000004', 'sample.read'),
  ('00000000-0000-0000-0000-000000000004', 'audit.read'),
  ('00000000-0000-0000-0000-000000000005', 'sample.read'),
  ('00000000-0000-0000-0000-000000000005', 'sample.checkout');
)FMGRSQL"},
      {4, "0004_layout",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS storage_containers (
  id TEXT PRIMARY KEY,
  lab_id TEXT NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  parent_id TEXT REFERENCES storage_containers(id) DEFERRABLE INITIALLY DEFERRED,
  kind TEXT NOT NULL CHECK (kind IN
    ('compartment', 'shelf', 'rack', 'drawer', 'custom')),
  name TEXT NOT NULL CHECK (length(name) > 0),
  label TEXT NOT NULL,
  ordering_index INTEGER NOT NULL DEFAULT 0,
  capacity_hint_json TEXT NOT NULL CHECK (json_valid(capacity_hint_json)),
  created_at_micros INTEGER NOT NULL,
  archived_at_micros INTEGER,
  CHECK (id <> parent_id)
);

CREATE INDEX IF NOT EXISTS storage_containers_parent_idx
  ON storage_containers(parent_id);
CREATE INDEX IF NOT EXISTS storage_containers_lab_idx
  ON storage_containers(lab_id);

CREATE TABLE IF NOT EXISTS freezers (
  id TEXT PRIMARY KEY,
  lab_id TEXT NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  name TEXT NOT NULL CHECK (length(name) > 0),
  location TEXT NOT NULL,
  model TEXT NOT NULL,
  temp_target_c REAL,
  layout_root_id TEXT NOT NULL
    REFERENCES storage_containers(id) DEFERRABLE INITIALLY DEFERRED,
  created_at_micros INTEGER NOT NULL,
  archived_at_micros INTEGER
);

CREATE INDEX IF NOT EXISTS freezers_lab_id_idx ON freezers(lab_id);
CREATE UNIQUE INDEX IF NOT EXISTS freezers_lab_name_unique
  ON freezers(lab_id, name) WHERE archived_at_micros IS NULL;
)FMGRSQL"},
      {5, "0005_box_types",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS container_types (
  id TEXT PRIMARY KEY,
  lab_id TEXT NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  name TEXT NOT NULL CHECK (length(name) > 0),
  size_class TEXT NOT NULL CHECK (length(size_class) > 0),
  outer_dimensions_json TEXT NOT NULL CHECK (json_valid(outer_dimensions_json)),
  material TEXT NOT NULL,
  supplier_sku TEXT NOT NULL,
  created_at_micros INTEGER NOT NULL,
  archived_at_micros INTEGER
);

CREATE INDEX IF NOT EXISTS container_types_lab_idx
  ON container_types(lab_id);
CREATE INDEX IF NOT EXISTS container_types_lab_size_class_idx
  ON container_types(lab_id, size_class);

CREATE TABLE IF NOT EXISTS box_types (
  id TEXT PRIMARY KEY,
  lab_id TEXT NOT NULL REFERENCES labs(id) DEFERRABLE INITIALLY DEFERRED,
  name TEXT NOT NULL CHECK (length(name) > 0),
  manufacturer TEXT NOT NULL,
  sku TEXT NOT NULL,
  created_at_micros INTEGER NOT NULL,
  archived_at_micros INTEGER
);

CREATE INDEX IF NOT EXISTS box_types_lab_idx
  ON box_types(lab_id);
CREATE UNIQUE INDEX IF NOT EXISTS box_types_lab_name_unique
  ON box_types(lab_id, name) WHERE archived_at_micros IS NULL;

CREATE TABLE IF NOT EXISTS box_type_positions (
  box_type_id TEXT NOT NULL
    REFERENCES box_types(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  label TEXT NOT NULL CHECK (length(label) > 0),
  row_index INTEGER NOT NULL CHECK (row_index >= 0),
  col_index INTEGER NOT NULL CHECK (col_index >= 0),
  z_index INTEGER CHECK (z_index IS NULL OR z_index >= 0),
  PRIMARY KEY (box_type_id, label)
);

CREATE TABLE IF NOT EXISTS box_type_position_accepts (
  box_type_id TEXT NOT NULL,
  position_label TEXT NOT NULL,
  size_class TEXT NOT NULL CHECK (length(size_class) > 0),
  PRIMARY KEY (box_type_id, position_label, size_class),
  FOREIGN KEY (box_type_id, position_label)
    REFERENCES box_type_positions(box_type_id, label)
    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
)FMGRSQL"},
      {6, "0006_boxes",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS boxes (
  id                   TEXT    PRIMARY KEY,
  lab_id               TEXT    NOT NULL REFERENCES labs(id)
                                 DEFERRABLE INITIALLY DEFERRED,
  box_type_id          TEXT    NOT NULL REFERENCES box_types(id)
                                 DEFERRABLE INITIALLY DEFERRED,
  storage_container_id TEXT    NOT NULL REFERENCES storage_containers(id)
                                 DEFERRABLE INITIALLY DEFERRED,
  label                TEXT    NOT NULL CHECK (length(label) > 0),
  serial               TEXT,
  barcode              TEXT,
  created_at_micros    INTEGER NOT NULL,
  archived_at_micros   INTEGER
);

CREATE INDEX IF NOT EXISTS boxes_lab_idx
  ON boxes(lab_id);
CREATE INDEX IF NOT EXISTS boxes_storage_container_idx
  ON boxes(storage_container_id);
CREATE INDEX IF NOT EXISTS boxes_box_type_idx
  ON boxes(box_type_id);
CREATE UNIQUE INDEX IF NOT EXISTS boxes_lab_label_unique
  ON boxes(lab_id, label) WHERE archived_at_micros IS NULL;
)FMGRSQL"},
      {7, "0007_item_types",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS item_types (
  id                 TEXT    PRIMARY KEY,
  lab_id             TEXT    NOT NULL REFERENCES labs(id)       DEFERRABLE INITIALLY DEFERRED,
  parent_id          TEXT             REFERENCES item_types(id) DEFERRABLE INITIALLY DEFERRED,
  name               TEXT    NOT NULL CHECK (length(name) > 0),
  created_at_micros  INTEGER NOT NULL,
  archived_at_micros INTEGER,
  CHECK (id <> parent_id)
);

CREATE INDEX IF NOT EXISTS item_types_lab_idx    ON item_types(lab_id);
CREATE INDEX IF NOT EXISTS item_types_parent_idx ON item_types(parent_id);
CREATE UNIQUE INDEX IF NOT EXISTS item_types_lab_name_unique
  ON item_types(lab_id, name) WHERE archived_at_micros IS NULL;

CREATE TABLE IF NOT EXISTS custom_field_definitions (
  id                 TEXT    PRIMARY KEY,
  lab_id             TEXT    NOT NULL REFERENCES labs(id)       DEFERRABLE INITIALLY DEFERRED,
  scope_kind         TEXT    NOT NULL
    CHECK (scope_kind IN ('sample', 'box', 'freezer', 'container')),
  item_type_id       TEXT             REFERENCES item_types(id) DEFERRABLE INITIALLY DEFERRED,
  key                TEXT    NOT NULL CHECK (length(key) > 0),
  label              TEXT    NOT NULL CHECK (length(label) > 0),
  data_type          TEXT    NOT NULL,
  required           INTEGER NOT NULL DEFAULT 0 CHECK (required IN (0, 1)),
  validation_json    TEXT    NOT NULL DEFAULT '{}',
  indexed            INTEGER NOT NULL DEFAULT 0 CHECK (indexed IN (0, 1)),
  is_phi             INTEGER NOT NULL DEFAULT 0 CHECK (is_phi IN (0, 1)),
  created_at_micros  INTEGER NOT NULL,
  archived_at_micros INTEGER
);

CREATE INDEX IF NOT EXISTS cfd_lab_idx  ON custom_field_definitions(lab_id);
CREATE INDEX IF NOT EXISTS cfd_type_idx ON custom_field_definitions(item_type_id);

CREATE UNIQUE INDEX IF NOT EXISTS cfd_lab_scope_type_key_unique
  ON custom_field_definitions(lab_id, scope_kind, COALESCE(item_type_id, ''), key)
  WHERE archived_at_micros IS NULL;
)FMGRSQL"},
      {8, "0008_samples",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS projects (
  id                 TEXT    PRIMARY KEY,
  lab_id             TEXT    NOT NULL REFERENCES labs(id)  DEFERRABLE INITIALLY DEFERRED,
  name               TEXT    NOT NULL CHECK (length(name) > 0),
  owner_user_id      TEXT    NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  created_at_micros  INTEGER NOT NULL,
  archived_at_micros INTEGER
);

CREATE INDEX  IF NOT EXISTS projects_lab_idx ON projects(lab_id);
CREATE UNIQUE INDEX IF NOT EXISTS projects_lab_name_unique
  ON projects(lab_id, name) WHERE archived_at_micros IS NULL;

CREATE TABLE IF NOT EXISTS samples (
  id                      TEXT    PRIMARY KEY,
  lab_id                  TEXT    NOT NULL REFERENCES labs(id)            DEFERRABLE INITIALLY DEFERRED,
  item_type_id            TEXT    NOT NULL REFERENCES item_types(id)      DEFERRABLE INITIALLY DEFERRED,
  name                    TEXT    NOT NULL CHECK (length(name) > 0),
  barcode                 TEXT,
  container_type_id       TEXT             REFERENCES container_types(id) DEFERRABLE INITIALLY DEFERRED,
  box_id                  TEXT             REFERENCES boxes(id)           DEFERRABLE INITIALLY DEFERRED,
  position_label          TEXT,
  volume_value            INTEGER,
  volume_unit             TEXT,
  mass_value              INTEGER,
  mass_unit               TEXT,
  status                  TEXT    NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'checked_out', 'depleted', 'destroyed', 'tombstoned')),
  parent_sample_id        TEXT             REFERENCES samples(id)         DEFERRABLE INITIALLY DEFERRED,
  created_by              TEXT    NOT NULL,
  created_at_micros       INTEGER NOT NULL,
  last_modified_by        TEXT    NOT NULL,
  last_modified_at_micros INTEGER NOT NULL,
  custom_fields_json      TEXT    NOT NULL DEFAULT '{}',
  phi_fields_enc_json     TEXT    NOT NULL DEFAULT '{}',
  CHECK ((box_id IS NULL) = (position_label IS NULL))
);

CREATE INDEX IF NOT EXISTS samples_lab_idx    ON samples(lab_id);
CREATE INDEX IF NOT EXISTS samples_box_idx    ON samples(box_id);
CREATE INDEX IF NOT EXISTS samples_parent_idx ON samples(parent_sample_id);
CREATE INDEX IF NOT EXISTS samples_status_idx ON samples(status);

CREATE UNIQUE INDEX IF NOT EXISTS samples_position_unique
  ON samples(box_id, position_label)
  WHERE status IN ('active', 'checked_out') AND box_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS sample_projects (
  sample_id  TEXT NOT NULL REFERENCES samples(id)  DEFERRABLE INITIALLY DEFERRED,
  project_id TEXT NOT NULL REFERENCES projects(id) DEFERRABLE INITIALLY DEFERRED,
  PRIMARY KEY (sample_id, project_id)
);

CREATE TABLE IF NOT EXISTS checkout_events (
  id             TEXT    PRIMARY KEY,
  sample_id      TEXT    NOT NULL REFERENCES samples(id) DEFERRABLE INITIALLY DEFERRED,
  lab_id         TEXT    NOT NULL REFERENCES labs(id)    DEFERRABLE INITIALLY DEFERRED,
  user_id        TEXT    NOT NULL REFERENCES users(id)   DEFERRABLE INITIALLY DEFERRED,
  action         TEXT    NOT NULL CHECK (action IN ('out', 'in', 'destroy')),
  reason         TEXT,
  at_micros      INTEGER NOT NULL,
  volume_delta   INTEGER,
  volume_unit    TEXT,
  location_after TEXT
);

CREATE INDEX IF NOT EXISTS checkout_events_sample_idx ON checkout_events(sample_id);
CREATE INDEX IF NOT EXISTS checkout_events_lab_idx    ON checkout_events(lab_id);
CREATE INDEX IF NOT EXISTS checkout_events_user_idx   ON checkout_events(user_id);
)FMGRSQL"},
      {9, "0009_share_requests",
       R"FMGRSQL(
CREATE TABLE IF NOT EXISTS share_requests (
  id                TEXT    PRIMARY KEY,
  source_lab_id     TEXT    NOT NULL REFERENCES labs(id)  DEFERRABLE INITIALLY DEFERRED,
  target_lab_id     TEXT    NOT NULL REFERENCES labs(id)  DEFERRABLE INITIALLY DEFERRED,
  requested_by      TEXT    NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  scope_json        TEXT    NOT NULL DEFAULT '{}',
  status            TEXT    NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'revoked')),
  created_at_micros  INTEGER NOT NULL,
  decided_at_micros  INTEGER,
  CHECK (source_lab_id != target_lab_id)
);

CREATE INDEX IF NOT EXISTS share_requests_source_lab_idx ON share_requests(source_lab_id);
CREATE INDEX IF NOT EXISTS share_requests_target_lab_idx ON share_requests(target_lab_id);
CREATE INDEX IF NOT EXISTS share_requests_status_idx     ON share_requests(status);

CREATE TABLE IF NOT EXISTS share_request_approvals (
  share_request_id  TEXT    NOT NULL REFERENCES share_requests(id) DEFERRABLE INITIALLY DEFERRED,
  approver_role     TEXT    NOT NULL
    CHECK (approver_role IN ('source_admin', 'target_admin', 'system_admin')),
  approver_user_id  TEXT    NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  decided_at_micros INTEGER NOT NULL,
  note              TEXT,
  PRIMARY KEY (share_request_id, approver_role)
);

CREATE INDEX IF NOT EXISTS share_request_approvals_request_idx
  ON share_request_approvals(share_request_id);
)FMGRSQL"},
      {10, "0010_sessions",
       R"FMGRSQL(
-- Server-side sessions and API tokens (D9).
-- token_prefix is the plaintext lookup key; token_hash is the Argon2id digest.
-- The auth layer generates the full random token, hashes it, and stores only
-- the hash.  No ON DELETE CASCADE: tombstones are set via revoked_at_micros.

CREATE TABLE IF NOT EXISTS sessions (
  id                    TEXT    PRIMARY KEY,
  user_id               TEXT    NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
  token_hash            TEXT    NOT NULL CHECK (length(token_hash) > 0),
  token_prefix          TEXT    NOT NULL CHECK (length(token_prefix) > 0),
  created_at_micros     INTEGER NOT NULL,
  last_seen_at_micros   INTEGER NOT NULL,
  ip                    TEXT,
  user_agent            TEXT,
  revoked_at_micros     INTEGER
);

-- Only one active session may use a given prefix at a time.
CREATE UNIQUE INDEX IF NOT EXISTS sessions_prefix_active_unique
  ON sessions(token_prefix) WHERE revoked_at_micros IS NULL;
CREATE INDEX IF NOT EXISTS sessions_user_id_idx
  ON sessions(user_id);

CREATE TABLE IF NOT EXISTS api_tokens (
  id                    TEXT    PRIMARY KEY,
  user_id               TEXT    NOT NULL REFERENCES users(id)  DEFERRABLE INITIALLY DEFERRED,
  lab_id                TEXT             REFERENCES labs(id)   DEFERRABLE INITIALLY DEFERRED,
  name                  TEXT    NOT NULL CHECK (length(name) > 0),
  scope_json            TEXT    NOT NULL DEFAULT '[]' CHECK (json_valid(scope_json)),
  token_hash            TEXT    NOT NULL CHECK (length(token_hash) > 0),
  token_prefix          TEXT    NOT NULL CHECK (length(token_prefix) > 0),
  created_at_micros     INTEGER NOT NULL,
  expires_at_micros     INTEGER,
  revoked_at_micros     INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS api_tokens_prefix_active_unique
  ON api_tokens(token_prefix) WHERE revoked_at_micros IS NULL;
CREATE INDEX IF NOT EXISTS api_tokens_user_id_idx ON api_tokens(user_id);
CREATE INDEX IF NOT EXISTS api_tokens_lab_id_idx  ON api_tokens(lab_id);
)FMGRSQL"},
      {11, "0011_audit_events",
       R"FMGRSQL(
-- Replace the simple audit_events table introduced in 0001_init with the
-- full hash-chained schema required by PRD §7.3.
-- DROP is safe here because the 0001 table was a temporary bootstrap placeholder
-- with no production data.
DROP TABLE IF EXISTS audit_events;

CREATE TABLE audit_events (
  id               TEXT    PRIMARY KEY,
  at_micros        INTEGER NOT NULL,
  actor_user_id    TEXT    NOT NULL,
  actor_session_id TEXT    NOT NULL,
  lab_id           TEXT,
  action           TEXT    NOT NULL,
  entity_kind      TEXT    NOT NULL,
  entity_id        TEXT,
  before_json      TEXT    NOT NULL DEFAULT '{}',
  after_json       TEXT    NOT NULL DEFAULT '{}',
  request_id       TEXT    NOT NULL,
  prev_hash        TEXT    NOT NULL,
  this_hash        TEXT    NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS audit_events_at_idx          ON audit_events(at_micros);
CREATE INDEX IF NOT EXISTS audit_events_actor_idx       ON audit_events(actor_user_id);
CREATE INDEX IF NOT EXISTS audit_events_entity_kind_idx ON audit_events(entity_kind);
CREATE INDEX IF NOT EXISTS audit_events_lab_idx         ON audit_events(lab_id);

-- Immutability triggers: the hash chain must never be altered.
CREATE TRIGGER IF NOT EXISTS audit_events_no_update
  BEFORE UPDATE ON audit_events
  FOR EACH ROW
  BEGIN
    SELECT RAISE(ABORT, 'audit_events is append-only: updates are not permitted');
  END;

CREATE TRIGGER IF NOT EXISTS audit_events_no_delete
  BEFORE DELETE ON audit_events
  FOR EACH ROW
  BEGIN
    SELECT RAISE(ABORT, 'audit_events is append-only: deletes are not permitted');
  END;
)FMGRSQL"},
      {12, "0012_sessions_mfa",
       R"FMGRSQL(
-- E2: Add MFA completion tracking to sessions.
-- Existing rows default to 1 (mfa_complete = true) so that previously
-- created sessions remain valid after the migration.
ALTER TABLE sessions ADD COLUMN mfa_complete INTEGER NOT NULL DEFAULT 1;
)FMGRSQL"},
      {13, "0013_authz_version",
       R"FMGRSQL(
-- Authorization epoch for cache invalidation. Bumped in-transaction whenever a
-- user's effective permissions change (membership/role/grant). Auth providers
-- key their resolved-permission cache on this value so a downgrade takes effect
-- on the next request rather than waiting for the cache TTL. Existing rows start
-- at 0; any later authz change increments it.
ALTER TABLE users ADD COLUMN authz_version INTEGER NOT NULL DEFAULT 0;
)FMGRSQL"},
      {14, "0014_lab_provision",
       R"FMGRSQL(
-- Global-only permission for deployment-level lab provisioning (LabService/CreateLab).
-- Creating a brand-new lab cannot be gated by a per-lab permission because no
-- membership exists yet; it is a SystemAdmin deployment action. Granted to the
-- built-in SystemAdmin role only.
INSERT INTO permissions (key, description) VALUES
  ('lab.provision', 'Provision (create) new labs (SystemAdmin only).');
INSERT INTO role_permissions (role_id, permission_key) VALUES
  ('00000000-0000-0000-0000-000000000001', 'lab.provision');
)FMGRSQL"},
      {15, "0015_login_attempt",
       R"FMGRSQL(
-- C-1: Persistent login-lockout state. Failed-login counters must survive a
-- process restart, otherwise an attacker bypasses the account lockout by
-- bouncing freezerd. Keyed by lowercased email; not lab-scoped (the lockout
-- check runs pre-authentication, before any lab context exists), so no RLS.
-- One active row per email: a successful login clears the row via
-- cleared_at_micros; the partial unique index below allows a fresh active row
-- on the next failure while cleared rows are retained (mirrors sessions).
CREATE TABLE IF NOT EXISTS login_attempts (
  id                    TEXT    PRIMARY KEY,
  email                 TEXT    NOT NULL CHECK (length(email) > 0),
  failure_count         INTEGER NOT NULL DEFAULT 0,
  locked_until_micros   INTEGER,
  last_activity_micros  INTEGER NOT NULL,
  cleared_at_micros     INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS login_attempts_email_active_unique
  ON login_attempts(email) WHERE cleared_at_micros IS NULL;
)FMGRSQL"},
  }};

} // namespace fmgr::storage

#endif // FMGR_SQLITEMIGRATIONSEMBEDDED_H
