#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Generate an embedded-migrations C++ header from a directory of NNNN_name.sql
# files. Each migration's SQL body is emitted verbatim as a raw string literal so
# the checksum (blake2b over "version:name:up_sql") is byte-identical to the SQL
# file — this is what keeps already-applied migrations verifying after the SQL is
# moved out of the backend .cc.
#
# Usage: gen_migrations_header.py <migrations_dir> <out_header> <array_var>
#
# CMake regenerates the header at configure time (see src/storage/CMakeLists.txt);
# it is also committed so an editor/reviewer sees the embedded form. A unit test
# (migration_files_test) re-reads the .sql files and asserts they match the
# embedded bodies, so an edit to a .sql without regeneration fails CI.
import os, re, sys

DELIM = "FMGRSQL"

def main():
    mig_dir, out_header, array_var = sys.argv[1], sys.argv[2], sys.argv[3]
    files = sorted(f for f in os.listdir(mig_dir) if f.endswith(".sql"))
    entries = []
    for f in files:
        m = re.match(r"(\d{4})_.*\.sql$", f)
        if not m:
            raise SystemExit(f"migration file not NNNN_name.sql: {f}")
        version = int(m.group(1))
        name = f[:-4]  # strip .sql
        body = open(os.path.join(mig_dir, f), encoding="utf-8", newline="").read()
        if f'){DELIM}"' in body:
            raise SystemExit(f"{f}: body contains the raw-string delimiter")
        entries.append((version, name, body))
    entries.sort(key=lambda e: e[0])

    guard = "FMGR_" + os.path.basename(out_header).upper().replace(".", "_")
    lines = [
        "// SPDX-License-Identifier: AGPL-3.0-or-later",
        "//",
        f"// GENERATED by tools/gen_migrations_header.py from {mig_dir}/*.sql.",
        "// DO NOT EDIT. Edit the .sql files and regenerate.",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "storage/EmbeddedMigration.h"',
        "",
        "#include <array>",
        "",
        "namespace fmgr::storage {",
        "",
        f"  inline constexpr std::array<EmbeddedMigration, {len(entries)}> {array_var}{{{{",
    ]
    for version, name, body in entries:
        lines.append(f'      {{{version}, "{name}",')
        lines.append(f'       R"{DELIM}({body}){DELIM}"}},')
    lines.append("  }};")
    lines.append("")
    lines.append("} // namespace fmgr::storage")
    lines.append("")
    lines.append(f"#endif // {guard}")
    with open(out_header, "w", encoding="utf-8", newline="\n") as out:
        out.write("\n".join(lines) + "\n")

if __name__ == "__main__":
    main()
